# Generated by Django 4.2.7 on 2024-01-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='matn_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='matn_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='matn_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='mavzu_en',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='mavzu_ru',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='mavzu_uz',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='sarlavha_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='sarlavha_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='maqola',
            name='sarlavha_uz',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
